version: '2'

services:

  cron:
    build: ./cron
    environment:
      - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
  
  nginx:
    build: 
      context: ./nginx
      args:
        - SSL_GROUP_GID=1337
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl:/etc/nginx/ssl
      - acme_challenge_webroot:/var/www/acme_challenge_webroot
    command: ['nginx', '-g', 'daemon off;']
  
  certgen:
    build:
      context: ./certgen
      args:
        - SSL_GROUP_GID=1337
        - RSA_KEY_LENGTH=2048
        - ECDSA_KEY_LENGTH=ec-256
    command: ['noop']
    volumes:
      - ssl:/opt/ssl
      - letsencrypt:/etc/letsencrypt
      - acme:/etc/acme
      - acme_challenge_webroot:/opt/acme_challenge_webroot
      
volumes:
  letsencrypt:
  acme:
  ssl:
  acme_challenge_webroot: